services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'testdb'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpassword'
    ports:
      - '5432'
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
