spring:
  security:
    user:
      name: test
      password: test
  kafka:
    streams:
      application-id: kafka-demo
  application:
    name: demo
  datasource:
    url: jdbc:tc:postgres:latest:///test
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: dev
rate:
  filePath: classpath:rate.csv
secrets:
  jwt: a-string-secret-at-least-256-bits-long