spring:
  application:
    name: demo
  datasource:
    url: jdbc:tc:postgres:latest:///test
#    username: test
#    password: test
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: dev
rate:
  filePath: classpath:rate.csv
#  source-url: