version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: mvn clean compile -f pom.xml
  test:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: mvn test -f pom.xml

workflows:
  say-hello-workflow:
    jobs:
      - build
      - test