version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Maven Build"
          command: mvn clean install
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Maven Test"
          command: mvn test

workflows:
  build-test-workflow:
    jobs:
      - build
      - test