version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0 # Or your desired Java image
    steps:
      - checkout
      - setup_remote_docker: # Required for Testcontainers with Docker executor
          docker_layer_caching: true
      - run:
          name: Set Testcontainers Host Override
          command: echo 'export TESTCONTAINERS_HOST_OVERRIDE=localhost' >> $BASH_ENV
      - run:
          name: Run Tests with Testcontainers
          command: ./mvnw clean verify
workflows:
  version: 2
  build:
    jobs:
      - build-and-test