version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: cimg/openjdk:21.0 # Or another suitable Java image
    steps:
      - checkout
      - setup_remote_docker # Essential for building Docker images
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }} # Example for Maven
            - maven-dependencies-
      - run: mvn clean install # Build Spring Boot JAR
      - save_cache:
          paths:
            - ~/.m2 # Example for Maven
          key: maven-dependencies-{{ checksum "pom.xml" }}
workflows:
  build-deploy-workflow:
    jobs:
      - build-and-deploy