version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  test:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: mvn test

workflows:
  say-hello-workflow:
    jobs:
      - build
      - test