version: 2.1

jobs:
  setup_workspace:
    docker:
      - image: maven:3.8.5-openjdk-21  # Use Maven with OpenJDK 11
    steps:
      - checkout  # Check out the source code
      - run:
          name: Setup Workspace
          command: |
            echo "Setting up workspace..."
            mkdir -p /home/circleci/project
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .

  build_test:
    docker:
      - image: maven:3.8.5-openjdk-21  # Use Maven with OpenJDK 11
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Build and Test Maven Application
          command: |
            mvn clean install  # Build and test the Maven application
workflows:
  version: 2
  ci_cd_pipeline:
    jobs:
      - setup_workspace
      - build_test:
          requires:
            - setup_workspace